[build]
  base = "frontend"
  command = "npm run dev"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://comnets-red-production.up.railway.app"
  VITE_WS_URL = "wss://comnets-red-production.up.railway.app"
