[build]
  base = "frontend"
  command = "npm ci --include=dev && node ./node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  VITE_BACKEND_URL = "https://comnets-red-production.up.railway.app"
  VITE_FRONTEND_URL = "https://comnets-red.netlify.app"
